config/routes.rb
Rails.application.routes.draw do
  get 'applications/index'
  post '/applications', to: 'applications#create'
  delete '/applications', to: 'applications#destroy'
  get 'keeps/index'
  post '/keeps', to: 'keeps#create'
  delete '/keeps', to: 'keeps#destroy'
  devise_for :users
  root 'pages#index'
  get 'posts/index'
  resources :posts, only: [:new, :show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keep.rb
class Keep < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :station, presence: true, length: { maximum: 255 }
  validates :location, presence: true, length: { maximum: 255 }
  validates :money, presence: true, length: { maximum: 255 }
  validates :hour, presence: true, length: { maximum: 255 }
  validates :description, presence: true, length: { maximum: 255 }

  has_many :keeps, dependent: :delete_all
  has_many :keep_users, through: :keeps, source: 'user'
  has_many :applications, dependent: :delete_all
  has_many :application_users, through: :applications, source: 'user'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :keeps, dependent: :delete_all
  has_many :keep_posts, through: :keeps, source: 'post'
  has_many :applications, dependent: :delete_all
  has_many :application_posts, through: :applications, source: 'post'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @application_posts = current_user.application_posts
  end

  def create
    application = current_user.applications.build(post_id: params[:post_id])

    if application.save
      redirect_to post_path(id: params[:post_id]), success: '申し込みが完了しました'
    else
      redirect_to post_path(id: params[:post_id]), danger: '申し込みできませんでした'
    end
  end

  def destroy
    application = Application.find_by(user_id: current_user, post_id: params[:post_id])
    application.destroy
    redirect_to applications_index_path, success: '申し込みをキャンセルしました'
  end
end

app/controllers/keeps_controller.rb
class KeepsController < ApplicationController
  before_action :authenticate_user!

  def index
    @keep_posts = current_user.keep_posts
  end

  def create
    keep = current_user.keeps.build(post_id: params[:post_id])

    if keep.save
      redirect_to post_path(id: params[:post_id]), success: 'キープに登録しました'
    else
      redirect_to post_path(id: params[:post_id]), danger: 'キープに失敗しました'
    end
  end

  def destroy
    keep = Keep.find_by(user_id: current_user, post_id: params[:post_id])
    keep.destroy
    redirect_to keeps_index_path, success: 'キープをやめました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @indexes = Post.all
    @posts =
      if params[:location].present?
        Post.where('location LIKE ?', "%#{params[:location]}%")
      end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_url, success: '投稿に成功しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :money, :hour, :station, :location, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    html = ''
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/applications/index.html.erb
<div class="container ">
  <div class="row border-bottom border-secondary my-5">
    <div class="h1 col-md-7">申し込み一覧</div>
    <div class="col-md-5"></div>
  </div>
  <div class="row">
    <!ここからeach文---->
      <% @application_posts.each do |post| %>
      <div class="col-md-1"></div>
      <div class="card col-md-5 mb-3 shadow">
        <div class="card-body">
          <h4 class="card-title">
            <%= post.title %>
          </h4>
          <p class="card-text">
            <%= "・最寄駅　　#{post.station}" %>
          </p>
          <p class="card-text">
            <%= "・時給　　　#{post.money}円" %>
          </p>
          <p class="card-text">
            <%= "・時間　　　#{post.hour}" %>
          </p>
          <%= link_to "詳細を見る", post_path(id: post.id), class:"card-link text-success"%>
          <%= link_to "申し込みをキャンセル", applications_path(post_id: post.id), method: :delete, class:"card-link text-success"%>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/keeps/index.html.erb
<div class="container ">
    <div class="row border-bottom border-secondary my-5">
        <div class="h1 col-md-7">キープ一覧</div>
        <div class="col-md-5"></div>
    </div>
    <div class="row">
        <!ここからeach文---->
            <% @keep_posts.each do |post| %>
            <div class="col-md-1"></div>
            <div class="card col-md-5 mb-3 shadow">
                <div class="card-body">
                    <h4 class="card-title">
                        <%= post.title %>
                    </h4>
                    <p class="card-text">
                        <%= "・最寄駅　　#{post.station}" %>
                    </p>
                    <p class="card-text">
                        <%= "・時給　　　#{post.money}円" %>
                    </p>
                    <p class="card-text">
                        <%= "・時間　　　#{post.hour}" %>
                    </p>
                    <%= link_to "詳細を見る", post_path(id: post.id), class:"card-link text-success"%>
                    <%= link_to "キープをやめる", keeps_path(post_id: post.id), method: :delete, class:"card-link text-success"%>  
                    
                </div>
            </div>
            <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8" />
    <title>StartResearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 100px;">
    
    <% flash.each do |type,msg| %>
      <% next if type == 'timedout' %>
      <div class="alert alert-<%=type%> " role="alert"><%= msg %></div>
    <% end %>

    <nav class="navbar navbar-light navbar-expand-lg fixed-top shadow">
        <%= link_to root_path, class: "navbar-brand text-success" do %>
            <%= image_tag 'logo.png' %>
        <% end %>       
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNav">
            <% if user_signed_in? %>
               <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <%= link_to '求人一覧', posts_index_path, class:"nav-link text-success" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'キープ一覧', keeps_index_path, class:"nav-link text-success" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '申し込み一覧', applications_index_path, class:"nav-link text-success" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '新規求人投稿', new_post_path, class:"nav-link text-success" %>
                  </li>
               </ul>
               <ul class="navbar-nav">
                 <li>
                     <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link text-success" %>  
                 </li>    
               </ul>
            <% else %>
               <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <%= link_to '求人一覧', posts_index_path, class:"nav-link text-success" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '新規求人投稿', new_post_path, class:"nav-link text-success" %>
                  </li>
               </ul>
               <ul class="navbar-nav">
                 <li>
                    <%= link_to '会員登録', new_user_registration_path, class:"nav-link text-success" %>
                 </li>  
                 <li>
                    <%= link_to 'ログイン', new_user_session_path, class:"nav-link text-success" %>
                 </li>  
               </ul>
               
            <% end %>
         </div>
    </nav>
    
    <%= yield %>
    
    <div class="container-fluid footer mt-5">
      <div class="row bg-light py-4 mt-5">
        <div class="col-md-12 text-center ">
          © 2020 StartResearch
        </div>
      </div>
    </div>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div class="row top-wrapper">
    <div class="col-md-1"></div>
    <div class="col-md-7 display-3 text-center text-success font-weight-bold">
      被験者バイトは
    </div>
    <div class="col-md-4"></div>
  </div>
  <div class="row bg-success middle-wrapper">
    <div class="col-md-2"></div>
    <div
      class="col-md-10 display-2 text-center pt-1 text-light font-weight-bold responsive-design"
    >
      StartResearch
    </div>
  </div>
  <div class="row py-5 my-5">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h3 class="text-center">
        <span class="markerDeepGreen"
          >StartResearchは空いた時間に、働きたい人と、</span
        >
      </h3>
      <h3 class="text-center">
        <span class="markerDeepGreen"
          >被験者を探している研究機関をつなぐ被験者バイトアプリです。</span
        >
      </h3>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12  text-center my-5">
      <h1>エリア別検索</h1>
    </div>

  </div>
  <%= form_with url: posts_index_path, method: :get, local: true do |f| %>
　  <div class="row">
      <div class="col-md-8 offset-md-1 ">
        <%= f.text_field :location , placeholder: 'ex)  東京都  新宿区' ,class: 'form-control border-success' %>
      </div>
      <div class="col-md-2 no-padding">
        <%= f.submit '検索', class: 'btn btn-block btn-success' %>
      </div>
    </div>
  <% end %>

</div>




<div class="container" id="test">
  <div class="row  mt-5 mb-5">

    <!ここからeach文---->
      <% @posts&.each do |post| %>
      <div class="card col-md-5 offset-md-1 mb-3 shadow">
        <div class="card-body">
          <h4 class="card-title">
            <%= post.title %>
          </h4>
          <p class="card-text">
            <%= "・最寄駅　　#{post.station}" %>
          </p>
          <p class="card-text">
            <%= "・時給　　　#{post.money}円" %>
          </p>
          <p class="card-text">
            <%= "・時間　　　#{post.hour}" %>
          </p>
          <%= link_to "詳細を見る", post_path(post.id), class:"card-link text-success"%>

        </div>
      </div>
      <% end %>

  </div>
</div>




<div class="container ">
  <div class="row border-bottom border-secondary mb-5">
    <div class="h1 col-md-7">求人一覧</div>
    <div class="col-md-5"></div>
  </div>
  <div class="row">
    <!ここからeach文---->
      <% @indexes.each do |post| %>
      <div class="card col-md-5 offset-md-1 mb-3 shadow">
        <div class="card-body">
          <h4 class="card-title">
            <%= post.title %>
          </h4>
          <p class="card-text">
            <%= "・最寄駅　　#{post.station}" %>
          </p>
          <p class="card-text">
            <%= "・時給　　　#{post.money}円" %>
          </p>
          <p class="card-text">
            <%= "・時間　　　#{post.hour}" %>
          </p>
          <%= link_to "詳細を見る", post_path(id: post.id), class:"card-link text-success"%>
          
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <div class="row ">
    <div class="col-md-6 offset-md-3 mb-5 pb-5  border border-success shadow">
      <h1 class="text-center my-5 ">新規求人投稿</h1>
      <%= form_for @post do |f| %>

      <div class="form-group">
        <%= f.label :title, "タイトル"%>
        <%= f.text_field :title, placeholder: 'ex) 心理学実験' , class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :money, "時給" %>
        <%= f.text_field :money, placeholder: 'ex) 1200' , class: 'form-control form-control-sm' %>
      </div>

      <div class="form-group">
        <%= f.label :hour, "勤務時間" %>
        <%= f.text_field :hour, placeholder: 'ex) 12:00-17:00' , class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :station, "最寄駅" %>
        <%= f.text_field :station, placeholder: 'ex) 新宿' , class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :location, "住所" %>
        <%= f.text_field :location, placeholder: 'ex) xx県yy市zz町1-2-3' , class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description, "その他条件" %>
        <%= f.text_area :description, placeholder: 'ex) 20才以上 女性' , class: 'form-control' %>
        <small class='form-text'>＊特に無い場合は「特に無し」と書いてください</small>
      </div>

      <%= f.submit '投稿', class: 'btn btn-light btn-block mt-5' %>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row ">
      <div class="col-lg-4 h2 pb-2 mt-5 border-bottom border-secondary">
         <%= @post.title%>
      </div>
      <div class="col-lg-3 mt-5"></div>
      <% if user_signed_in? %>
        <% if @post.keep_users.include?(current_user) && @post.application_users.include?(current_user) %>
           <div class="col-lg-2 h4">
             <span class="badge badge-success d-block mt-3 badge_p">キープ済み</span>
           </div>
           <div class="col-lg-3 h4">
             <span class="badge badge-success d-block mt-3 badge_p">申し込み済み</span>
           </div>
        <% elsif !@post.keep_users.include?(current_user) && @post.application_users.include?(current_user) %>
           <div class="col-lg-2 mt-3">
              <%= link_to "キープする", keeps_path(post_id: @post.id), method: :post, class: 'btn btn-block btn-light btn-show' %>
           </div>
           <div class="col-lg-3 h4">
             <span class="badge badge-success d-block mt-3 badge_p">申し込み済み</span>
           </div>
        <% elsif @post.keep_users.include?(current_user) && !@post.application_users.include?(current_user)%>
           <div class="col-lg-2 h4">
             <span class="badge badge-success d-block mt-3 badge_p">キープ済み</span>
           </div>
           <div class="col-lg-3 mt-3">
              <%= link_to "申し込む", applications_path(post_id: @post.id), method: :post, class: 'btn btn-block btn-light btn-show' %>
           </div>
        <% else %>
           <div class="col-lg-2 mt-3">
              <%= link_to "キープする", keeps_path(post_id: @post.id), method: :post, class: 'btn btn-block btn-light btn-show' %>
           </div>
           <div class="col-lg-3 mt-3">
              <%= link_to "申し込む", applications_path(post_id: @post.id), method: :post, class: 'btn btn-block btn-light btn-show' %>
           </div>
        <% end %>
      <% else %>
        <div class="col-lg-2"></div>
        <div class="col-lg-3"></div>
      <% end %>
  </div>
  <div class="row mt-5 pt-5"> 
      <div class="col-lg-2 h3 ">
         <span class="badge badge-success">時給</span>
      </div>   
      <div class="col-lg-10 h3 ">
         <%= "#{@post.money}円"%>
      </div>
  </div>
  <div class="row mt-5 pt-5"> 
      <div class="col-lg-2 h3">
         <span class="badge badge-success">時間</span>
      </div>
      <div class="col-lg-10 h3 ">
         <%= "#{@post.hour}"%>
      </div>
  </div>
  <div class="row mt-5 pt-5"> 
      <div class="col-lg-2 h3 ">
         <span class="badge badge-success">最寄駅</span>
      </div>
      <div class="col-lg-10 h3 ">
         <%= "#{@post.station}"%>
      </div>
  </div>
  <div class="row mt-5 pt-5"> 
      <div class="col-lg-2 h3">
         <span class="badge badge-success">住所</span>
      </div>
      <div class="col-lg-10 h3 ">
         <%= "#{@post.location}"%>
      </div>
  </div>
  <div class="row my-5 pt-5"> 
      <div class="col-lg-2 h3 ">
         <span class="badge badge-success">その他条件</span>
      </div>   
      <div class="col-lg-10 h3 ">
         <%= "#{@post.description}"%>
      </div>
  </div>
</div>